/* automatically generated by rust-bindgen 0.64.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct A {
    pub a: ::std::os::raw::c_int,
    pub ptr: *mut ::std::os::raw::c_void,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct B {
    pub _base: A,
    pub b: ::std::os::raw::c_int,
}