/* automatically generated by rust-bindgen 0.64.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo {
    pub data: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct Bar {
    pub data: usize,
}

extern "C" {
    #[link_name = "\u{1}_Z7MakeFoov"]
    pub fn MakeFoo() -> Foo;
}

extern "C" {
    #[link_name = "\u{1}_Z7MakeBarv"]
    pub fn MakeBar() -> Bar;
}

#[no_mangle]
pub extern "C" fn root() {
    unsafe {
        let f = MakeFoo();
        let b = MakeBar();
    }
}