/* automatically generated by rust-bindgen 0.65.1 */

extern "C" {
    #[link_name = "\u{1}_Z5hellov"]
    pub fn hello();
}
extern "C" {
    #[link_name = "\u{1}_Z8overridev"]
    pub fn override_();
}
extern "C" {
    #[link_name = "\u{1}_Z8overridei"]
    pub fn override_1(d: ::std::os::raw::c_int);
}
