/* automatically generated by rust-bindgen 0.64.0 */

#[repr(C)]
pub struct Foo {
    pub data: usize,
}

#[repr(C)]
pub struct Bar {
    pub data: usize,
}

extern "C" {
    pub fn MakeFoo() -> Foo;
}

extern "C" {
    pub fn MakeBar() -> Bar;
}

#[no_mangle]
pub extern "C" fn root() {
    unsafe {
        let f = MakeFoo();
        let b = MakeBar();
    }
}