/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct A {
    pub ptr: *mut ::std::os::raw::c_void,
    pub _m_buf: ::std::os::raw::c_int,
}

extern "C" {
    #[link_name = "\u{1}_ZNK1A9say_helloEv"]
    pub fn A_say_hello(this: *const A);
}
extern "C" {
    #[link_name = "\u{1}_ZN1AC1Ev"]
    pub fn A_A(this: *mut A);
}
impl A {
    #[inline]
    pub unsafe fn say_hello(&self) {
        A_say_hello(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        A_A(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
}
#[repr(C)]
#[derive(Debug, Clone)]
pub struct B {
    pub _base: A,
    pub _m_val: ::std::os::raw::c_int,
}

extern "C" {
    #[link_name = "\u{1}_ZNK1B9say_helloEv"]
    pub fn B_say_hello(this: *const B);
}
extern "C" {
    #[link_name = "\u{1}_ZN1BC1Ev"]
    pub fn B_B(this: *mut B);
}
impl B {
    #[inline]
    pub unsafe fn say_hello(&self) {
        B_say_hello(self)
    }
    #[inline]
    pub unsafe fn new() -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        B_B(__bindgen_tmp.as_mut_ptr());
        __bindgen_tmp.assume_init()
    }
}

// pub struct A {
//     pub id: i32,
//     pub data: [i64; 10]
// }

// fn main() {
//     let a = A { id: 1, data: [0; 10] };
// }