[package]
name = "ABIChecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { version = "0.1.0", features = ["llvm15-0"] }

collect_cxx = { path = "collector/collect_cxx" }
collect_rust = { path = "collector/collect_rust" }