[package]
name = "ABIChecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell = { version = "0.1.0", features = ["llvm15-0"] }
bindgen_cxx_parser = { path = "/home/ubuntu/Desktop/RustCLA/ABIChecker/collector/bindgen" }