/* automatically generated by rust-bindgen 0.64.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct T {
    pub a: ::std::os::raw::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct A {
    pub a: ::std::os::raw::c_int,
    pub b: ::std::os::raw::c_int,
    pub t: T,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct B {
    pub opaque: [::std::os::raw::c_int; 2]
}

pub extern "C" fn root(a: A, b: B) {

}