[package]
name = "collect_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen_rust_parser = { path = "../../modified_deps/bindgen" }