/* automatically generated by rust-bindgen 0.65.1 */

#[repr(C)]
#[derive(Debug)]
pub struct A {
    pub data: *mut ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_A() {
    const UNINIT: ::std::mem::MaybeUninit<A> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<A>(),
        8usize,
        concat!("Size of: ", stringify!(A))
    );
    assert_eq!(
        ::std::mem::align_of::<A>(),
        8usize,
        concat!("Alignment of ", stringify!(A))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        0usize,
        concat!("Offset of field: ", stringify!(A), "::", stringify!(data))
    );
}
extern "C" {
    #[link_name = "\u{1}_ZN1A4funcEv"]
    pub fn A_func(this: *mut A);
}
extern "C" {
    #[link_name = "\u{1}_ZN1AC1Ei"]
    pub fn A_A(this: *mut A, size: ::std::os::raw::c_int);
}
extern "C" {
    #[link_name = "\u{1}_ZN1AD1Ev"]
    pub fn A_A_destructor(this: *mut A);
}
impl A {
    #[inline]
    pub unsafe fn func(&mut self) {
        A_func(self)
    }
    #[inline]
    pub unsafe fn new(size: ::std::os::raw::c_int) -> Self {
        let mut __bindgen_tmp = ::std::mem::MaybeUninit::uninit();
        A_A(__bindgen_tmp.as_mut_ptr(), size);
        __bindgen_tmp.assume_init()
    }
    #[inline]
    pub unsafe fn destruct(&mut self) {
        A_A_destructor(self)
    }
}
